/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_nuance_FastText */

#ifndef _Included_com_nuance_FastText
#define _Included_com_nuance_FastText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nuance_FastText
 * Method:    predictLine
 * Signature: (Ljava/lang/String;JIF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nuance_FastText_predictLine
  (JNIEnv *, jobject, jstring, jlong, jint, jfloat);

/*
 * Class:     com_nuance_FastText
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nuance_FastText_loadModel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
