/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_nuance_FastText */

#ifndef _Included_com_nuance_FastText
#define _Included_com_nuance_FastText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nuance_FastText
 * Method:    predictLine
 * Signature: (Ljava/lang/String;Ljava/lang/String;IF)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_nuance_FastText_predictLine
  (JNIEnv *, jobject, jstring, jstring, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
